address = "9567 Turner Trace Apt. BC C3G8A4"
author = "Intelops"
career_form_action = "#!"
contact_form_action = "#!"
custom_script = ""
description = "This is meta description"
email = "info@email.com"
favicon = "images/favicon-intelops.png"
image = "images/logo.png"
logo = "images/logo-dark.png"
logo_light = "images/logo-light.png"
logo_text = "Intelops"
logo_width = "147x"
mainSections = ["blog"]
mobile = "+211234565523"
fullSiteSearch = true
[call_to_action]
button_label = "Contact Us"
button_link = "contact/"
enable = true
image = "images/develop.png"
subtitle = "We heard the pain of building the Talent, keeping up with Concepts, Culture, Technology and Tools. We have been there! Hence, we built the new Ai-based automated solution to solve the problems for everyone."
title = "Looking for Cloud-Native Talent? <br> Let us make your life easy!"
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[navigation_button]
enable = true
icon = "far fa-user"
label = "Log In"
link = "#!"
[navigation_button_two]
enable = true
label = "Sign Up Now"
link = "#!"
[preloader]
enable = true
preloader = "images/loader.png"
[[social]]
icon = "fab fa-facebook"
link = "#!"
title = "facebook"
[[social]]
icon = "fab fa-twitter"
link = "#!"
title = "twitter"
[[social]]
icon = "fab fa-instagram"
link = "#!"
title = "instagram"
[[social]]
icon = "fab fa-github"
link = "#!"
title = "github"
[[social]]
icon = "fab fa-linkedin"
link = "#!"
title = "linkedin"